spring:
  profiles:
    active: dockermongo

# using profiles
---

spring:
  data:
    mongodb:
      authentication-database: admin
      username: username
      password: password
      database: dbName
      port: 27017
      host: mongodb+srv://username:password@cluster0.fs7om.mongodb.net:port/dbName
      auto-index-creation: true
  config:
    activate:
      on-profile: cloudmongo

---

spring:
  data:
    mongodb:
      authentication-database: admin
      username: rootuser
      password: rootpass
      database: peyhub
      port: 27017
      host: localhost
      auto-index-creation: true
  config:
    activate:
      on-profile: dockermongo

---
