spring:
  profiles:
    active: dockermongo

# using profiles
---

spring:
  data:
    mongodb:
      host: [host]
      port: [port]
      authentication-database: [authentication_database]
      username: [username]
      password: [password]
      database: [db_name]
  config:
    activate:
      on-profile: cloudmongo

---

spring:
  data:
    mongodb:
      authentication-database: admin
      username: rootuser
      password: rootpass
      database: peyhub
      port: 27017
      host: localhost
      auto-index-creation: true
  config:
    activate:
      on-profile: dockermongo

---
